export { refs };
const refs = {
  gallery: document.querySelector('.js-gallery__list'),
  backdrop: document.querySelector('#backdrop'),
  body: document.querySelector('body'),
  btnCloseModalFilm: document.querySelector('#btn-close-modal'),
  imageModal: document.querySelector('#imageModal'),
  modalTitle: document.querySelector('#title'),
  modalTitleOriginal: document.querySelector('#titleOriginal'),
  voteModal: document.querySelector('#vote'),
  votesModal: document.querySelector('#votes'),
  popularityModal: document.querySelector('#popularity'),
  genreModal: document.querySelector('#genre'),
  overviewModal: document.querySelector('#overview'),
  gallery: document.querySelector('.js-gallery__list'),
  modalBtn: document.querySelector('.js-modal-button'),
  searchForm: document.querySelector('.search'),
  searchError: document.querySelector('.search-error'),
  searchFormContainer: document.querySelector('.search-form-container'),
  modalBtnWatched: document.querySelector('[data-actions="watched"]'),
  modalBtnQueue: document.querySelector('[data-actions="queue"]'),
};
